project:
  type: website
  output-dir: .

website:
  title: "PHYS 211"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://phys211.github.io/Fall2024/
        text: "Fall 2024" 
        target: _blank #makes it open in new page

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
self-contained: true


